"""Typed explanation output contract."""

from pydantic import BaseModel, ConfigDict, Field


class Explanation(BaseModel):
    """Human-readable explanation fields generated by the coach agent."""

    model_config = ConfigDict(extra="forbid", frozen=True, str_strip_whitespace=True)

    summary: str = Field(..., min_length=1)
    detail: str = Field(..., min_length=1)
    adjustment_breakdown: str = Field(..., min_length=1)
    backup_note: str = Field(..., min_length=1)
